### ISSUE TITLE
Final feedback

### ISSUE THREAD

**Issue by zeliard** [mooneegee/ChopTheBeats#132]
다 준비 못했더라도 오늘 최종 시연만큼은 나와서 하지 그랬남...

다들 고생 많았고, 이번 프로젝트는 이렇게 마무리 하는걸로 하자고..

@mooneegee @LeeInJae @nhnponyo 는 내년에 어떻게 할지 계획 잘 세워 보고,
지훈이는 어느 테크트리를 탈지 잘 고민해보기 바란다.

한 학기 수고 많았다.

**Comment by mooneegee** [comment]
확인이 늦었습니다.
프로젝트가 잘 진행되지 않아서 죄송합니다.
한 학기동안 감사했습니다.
